name: CI/CD
on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: ghactions-codenoobs
  AZURE_WEBAPP_PACKAGE_PATH: "build"
  NODE_VERSION: "14.x"
  ARTIFACT_NAME: react-webapp

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install, Build & Tests ğŸ”§âœ…
        run: |
          npm install
          npm run-script build 
          npm run-script test

      - name: Upload Built WebApp â¬†
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: build
  staging:
    name: Deploy to STG
    needs: build
    runs-on: ubuntu-latest
  Â Â environment:
Â Â Â Â Â Â   name: staging
Â Â Â Â Â Â   url: ${{ steps.deploy_staging.outputs.webapp-url }}
    steps:
      - name: Download Built WebApp â¬‡
        uses: actions/download-artifact@v1
        with:
          name:  ${{ env.ARTIFACT_NAME }}

      - name: Deploy to Azure WebApp ğŸš€
        uses: azure/webapps-deploy@v2
        id: deploy_staging
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          slot-name: staging

   deploy:
    name: Deploy to PRD
    needs: staging
    runs-on: ubuntu-latest
    environment:
        name: production
        url: ${{ steps.deploy_production.outputs.webapp-url }}
    steps:
      - name: Download Built WebApp â¬‡
        uses: actions/download-artifact@v1
        with:
          name:  ${{ env.ARTIFACT_NAME }}

    - name: Deploy to Azure WebAppğŸš€
      id: deploy_production
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}

