name: Master CI/CD
on:
  push:
    branches:
      - master

env:
  PACKAGE_PATH: ./build
  NODE_VERSION: 14.x
  ARTIFACT_NAME: react-webapp

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install, Build & Tests ğŸ”§âœ…
        run: |
          npm install
          npm run-script build 
          npm run-script test

      - name: Upload Built WebApp â¬†
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.PACKAGE_PATH }}
  commit:
    needs: build
    name: Commit on GH-Pages branch
    runs-on: ubuntu-latest
    steps:
      - name: Download Built WebApp â¬‡
        uses: actions/download-artifact@v1
        with:
          name: ${{ env.ARTIFACT_NAME }}

      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          ref: gh-pages

      - name: Commiting changes ğŸ“ƒ
        run: |
          git add ${{ env.ARTIFACT_PATH }}
          git commit -m "New feature is released"